// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: testdata/foo.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Foo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"ID,omitempty" gorm:"column:id;autoIncrement"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" gorm:"column:id;type:text"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Foo) Reset() {
	*x = Foo{}
	mi := &file_testdata_foo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_foo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_testdata_foo_proto_rawDescGZIP(), []int{0}
}

func (x *Foo) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Foo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_testdata_foo_proto protoreflect.FileDescriptor

const file_testdata_foo_proto_rawDesc = "" +
	"\n" +
	"\x12testdata/foo.proto\x12\btestdata\")\n" +
	"\x03foo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB\fZ\n" +
	"./testdatab\x06proto3"

var (
	file_testdata_foo_proto_rawDescOnce sync.Once
	file_testdata_foo_proto_rawDescData []byte
)

func file_testdata_foo_proto_rawDescGZIP() []byte {
	file_testdata_foo_proto_rawDescOnce.Do(func() {
		file_testdata_foo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_foo_proto_rawDesc), len(file_testdata_foo_proto_rawDesc)))
	})
	return file_testdata_foo_proto_rawDescData
}

var file_testdata_foo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testdata_foo_proto_goTypes = []any{
	(*Foo)(nil), // 0: testdata.foo
}
var file_testdata_foo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testdata_foo_proto_init() }
func file_testdata_foo_proto_init() {
	if File_testdata_foo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_foo_proto_rawDesc), len(file_testdata_foo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_foo_proto_goTypes,
		DependencyIndexes: file_testdata_foo_proto_depIdxs,
		MessageInfos:      file_testdata_foo_proto_msgTypes,
	}.Build()
	File_testdata_foo_proto = out.File
	file_testdata_foo_proto_goTypes = nil
	file_testdata_foo_proto_depIdxs = nil
}
