// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: testdata/message.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupRole int32

const (
	GroupRoleUnspecific    GroupRole = 0
	GroupRoleCreator       GroupRole = 1
	GroupRoleAdministrator GroupRole = 2
	GroupRoleViceOwner     GroupRole = 3
)

// Enum value maps for GroupRole.
var (
	GroupRole_name = map[int32]string{
		0: "UNSPECIFIC",
		1: "CREATOR",
		2: "ADMINISTRATOR",
		3: "VICE_OWNER",
	}
	GroupRole_value = map[string]int32{
		"UNSPECIFIC":    0,
		"CREATOR":       1,
		"ADMINISTRATOR": 2,
		"VICE_OWNER":    3,
	}
)

func (x GroupRole) Enum() *GroupRole {
	p := new(GroupRole)
	*p = x
	return p
}

func (x GroupRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupRole) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_message_proto_enumTypes[0].Descriptor()
}

func (GroupRole) Type() protoreflect.EnumType {
	return &file_testdata_message_proto_enumTypes[0]
}

func (x GroupRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupRole.Descriptor instead.
func (GroupRole) EnumDescriptor() ([]byte, []int) {
	return file_testdata_message_proto_rawDescGZIP(), []int{0}
}

type MessageState int32

const (
	MessageStateOffline   MessageState = 0
	MessageStateOnline    MessageState = 1
	MessageStateInvisible MessageState = 2
)

// Enum value maps for MessageState.
var (
	MessageState_name = map[int32]string{
		0: "OFFLINE",
		1: "ONLINE",
		2: "INVISIBLE",
	}
	MessageState_value = map[string]int32{
		"OFFLINE":   0,
		"ONLINE":    1,
		"INVISIBLE": 2,
	}
)

func (x MessageState) Enum() *MessageState {
	p := new(MessageState)
	*p = x
	return p
}

func (x MessageState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageState) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_message_proto_enumTypes[1].Descriptor()
}

func (MessageState) Type() protoreflect.EnumType {
	return &file_testdata_message_proto_enumTypes[1]
}

func (x MessageState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageState.Descriptor instead.
func (MessageState) EnumDescriptor() ([]byte, []int) {
	return file_testdata_message_proto_rawDescGZIP(), []int{2, 0}
}

type MessageManGender int32

const (
	MessageManGenderUnspecific MessageManGender = 0
	MessageManGenderMale       MessageManGender = 1
	MessageManGenderFemale     MessageManGender = 2
)

// Enum value maps for MessageManGender.
var (
	MessageManGender_name = map[int32]string{
		0: "UNSPECIFIC",
		1: "MALE",
		2: "FEMALE",
	}
	MessageManGender_value = map[string]int32{
		"UNSPECIFIC": 0,
		"MALE":       1,
		"FEMALE":     2,
	}
)

func (x MessageManGender) Enum() *MessageManGender {
	p := new(MessageManGender)
	*p = x
	return p
}

func (x MessageManGender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageManGender) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_message_proto_enumTypes[2].Descriptor()
}

func (MessageManGender) Type() protoreflect.EnumType {
	return &file_testdata_message_proto_enumTypes[2]
}

func (x MessageManGender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageManGender.Descriptor instead.
func (MessageManGender) EnumDescriptor() ([]byte, []int) {
	return file_testdata_message_proto_rawDescGZIP(), []int{2, 0, 0}
}

type Dog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dog) Reset() {
	*x = Dog{}
	mi := &file_testdata_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dog) ProtoMessage() {}

func (x *Dog) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dog.ProtoReflect.Descriptor instead.
func (*Dog) Descriptor() ([]byte, []int) {
	return file_testdata_message_proto_rawDescGZIP(), []int{0}
}

func (x *Dog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dog) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type Cat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Birth         int32                  `protobuf:"varint,3,opt,name=birth,proto3" json:"birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cat) Reset() {
	*x = Cat{}
	mi := &file_testdata_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cat) ProtoMessage() {}

func (x *Cat) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cat.ProtoReflect.Descriptor instead.
func (*Cat) Descriptor() ([]byte, []int) {
	return file_testdata_message_proto_rawDescGZIP(), []int{1}
}

func (x *Cat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cat) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Cat) GetBirth() int32 {
	if x != nil {
		return x.Birth
	}
	return 0
}

type Message struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"column:id;autoIncrement" bson:"_id"`
	Sequence   int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty" gorm:"column:sequence;type:bigint"`
	Addresser  int64                  `protobuf:"varint,3,opt,name=addresser,proto3" json:"addresser,omitempty" gorm:"column:addresser;type:bigint" bson:"Addresser"`
	Addressee  int64                  `protobuf:"varint,4,opt,name=addressee,proto3" json:"addressee,omitempty" gorm:"column:addressee;type:bigint"`
	Originator int64                  `protobuf:"varint,5,opt,name=originator,proto3" json:"originator,omitempty"`
	Timestamp  int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Flags      int32                  `protobuf:"varint,7,opt,name=flags,proto3" json:"flags,omitempty"`
	Platform   int32                  `protobuf:"varint,8,opt,name=platform,proto3" json:"platform,omitempty"`
	Category   int32                  `protobuf:"varint,9,opt,name=category,proto3" json:"category,omitempty"`
	Type       int32                  `protobuf:"varint,10,opt,name=type,proto3" json:"type,omitempty"`
	S1         string                 `protobuf:"bytes,11,opt,name=s1,proto3" json:"s1,omitempty"`
	S2         string                 `protobuf:"bytes,12,opt,name=s2,proto3" json:"s2,omitempty"`
	S3         string                 `protobuf:"bytes,13,opt,name=s3,proto3" json:"s3,omitempty"`
	S4         string                 `protobuf:"bytes,14,opt,name=s4,proto3" json:"s4,omitempty"`
	N1         int64                  `protobuf:"varint,15,opt,name=n1,proto3" json:"n1,omitempty"`
	N2         int64                  `protobuf:"varint,16,opt,name=n2,proto3" json:"n2,omitempty"`
	N3         int64                  `protobuf:"varint,17,opt,name=n3,proto3" json:"n3,omitempty"`
	N4         int64                  `protobuf:"varint,18,opt,name=n4,proto3" json:"n4,omitempty"`
	Quote      []byte                 `protobuf:"bytes,19,opt,name=quote,proto3" json:"quote,omitempty"`
	Extra      []byte                 `protobuf:"bytes,20,opt,name=extra,proto3" json:"extra,omitempty"`
	From       *MessageMan            `protobuf:"bytes,21,opt,name=from,proto3" json:"from,omitempty"`
	// @go.name=MyPet
	// @bson.tag=my_pet
	//
	// Types that are valid to be assigned to Pet:
	//
	//	*Message_Dog
	//	*Message_Cat
	Pet           isMessage_Pet `protobuf_oneof:"pet"`
	Role          GroupRole     `protobuf:"varint,24,opt,name=role,proto3,enum=testdata.GroupRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_testdata_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_testdata_message_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Message) GetAddresser() int64 {
	if x != nil {
		return x.Addresser
	}
	return 0
}

func (x *Message) GetAddressee() int64 {
	if x != nil {
		return x.Addressee
	}
	return 0
}

func (x *Message) GetOriginator() int64 {
	if x != nil {
		return x.Originator
	}
	return 0
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetFlags() int32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Message) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *Message) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *Message) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Message) GetS1() string {
	if x != nil {
		return x.S1
	}
	return ""
}

func (x *Message) GetS2() string {
	if x != nil {
		return x.S2
	}
	return ""
}

func (x *Message) GetS3() string {
	if x != nil {
		return x.S3
	}
	return ""
}

func (x *Message) GetS4() string {
	if x != nil {
		return x.S4
	}
	return ""
}

func (x *Message) GetN1() int64 {
	if x != nil {
		return x.N1
	}
	return 0
}

func (x *Message) GetN2() int64 {
	if x != nil {
		return x.N2
	}
	return 0
}

func (x *Message) GetN3() int64 {
	if x != nil {
		return x.N3
	}
	return 0
}

func (x *Message) GetN4() int64 {
	if x != nil {
		return x.N4
	}
	return 0
}

func (x *Message) GetQuote() []byte {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *Message) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *Message) GetFrom() *MessageMan {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Message) GetPet() isMessage_Pet {
	if x != nil {
		return x.Pet
	}
	return nil
}

func (x *Message) GetDog() *Dog {
	if x != nil {
		if x, ok := x.Pet.(*Message_Dog); ok {
			return x.Dog
		}
	}
	return nil
}

func (x *Message) GetCat() *Cat {
	if x != nil {
		if x, ok := x.Pet.(*Message_Cat); ok {
			return x.Cat
		}
	}
	return nil
}

func (x *Message) GetRole() GroupRole {
	if x != nil {
		return x.Role
	}
	return GroupRoleUnspecific
}

type isMessage_Pet interface {
	isMessage_Pet()
}

type Message_Dog struct {
	Dog *Dog `protobuf:"bytes,22,opt,name=dog,proto3,oneof"`
}

type Message_Cat struct {
	Cat *Cat `protobuf:"bytes,23,opt,name=cat,proto3,oneof"`
}

func (*Message_Dog) isMessage_Pet() {}

func (*Message_Cat) isMessage_Pet() {}

type MessageMan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UName         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"user_name,omitempty"`
	UA            int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageMan) Reset() {
	*x = MessageMan{}
	mi := &file_testdata_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageMan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMan) ProtoMessage() {}

func (x *MessageMan) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMan.ProtoReflect.Descriptor instead.
func (*MessageMan) Descriptor() ([]byte, []int) {
	return file_testdata_message_proto_rawDescGZIP(), []int{2, 0}
}

func (x *MessageMan) GetUName() string {
	if x != nil {
		return x.UName
	}
	return ""
}

func (x *MessageMan) GetUA() int32 {
	if x != nil {
		return x.UA
	}
	return 0
}

var File_testdata_message_proto protoreflect.FileDescriptor

const file_testdata_message_proto_rawDesc = "" +
	"\n" +
	"\x16testdata/message.proto\x12\btestdata\"+\n" +
	"\x03dog\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\"C\n" +
	"\x03cat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05birth\x18\x03 \x01(\x05R\x05birth\"\xec\x05\n" +
	"\amessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12\x1c\n" +
	"\taddresser\x18\x03 \x01(\x03R\taddresser\x12\x1c\n" +
	"\taddressee\x18\x04 \x01(\x03R\taddressee\x12\x1e\n" +
	"\n" +
	"originator\x18\x05 \x01(\x03R\n" +
	"originator\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05flags\x18\a \x01(\x05R\x05flags\x12\x1a\n" +
	"\bplatform\x18\b \x01(\x05R\bplatform\x12\x1a\n" +
	"\bcategory\x18\t \x01(\x05R\bcategory\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\x05R\x04type\x12\x0e\n" +
	"\x02s1\x18\v \x01(\tR\x02s1\x12\x0e\n" +
	"\x02s2\x18\f \x01(\tR\x02s2\x12\x0e\n" +
	"\x02s3\x18\r \x01(\tR\x02s3\x12\x0e\n" +
	"\x02s4\x18\x0e \x01(\tR\x02s4\x12\x0e\n" +
	"\x02n1\x18\x0f \x01(\x03R\x02n1\x12\x0e\n" +
	"\x02n2\x18\x10 \x01(\x03R\x02n2\x12\x0e\n" +
	"\x02n3\x18\x11 \x01(\x03R\x02n3\x12\x0e\n" +
	"\x02n4\x18\x12 \x01(\x03R\x02n4\x12\x14\n" +
	"\x05quote\x18\x13 \x01(\fR\x05quote\x12\x14\n" +
	"\x05extra\x18\x14 \x01(\fR\x05extra\x12)\n" +
	"\x04from\x18\x15 \x01(\v2\x15.testdata.message.manR\x04from\x12!\n" +
	"\x03dog\x18\x16 \x01(\v2\r.testdata.dogH\x00R\x03dog\x12!\n" +
	"\x03cat\x18\x17 \x01(\v2\r.testdata.catH\x00R\x03cat\x12'\n" +
	"\x04role\x18\x18 \x01(\x0e2\x13.testdata.GroupRoleR\x04role\x1a[\n" +
	"\x03man\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\".\n" +
	"\x06Gender\x12\x0e\n" +
	"\n" +
	"UNSPECIFIC\x10\x00\x12\b\n" +
	"\x04MALE\x10\x01\x12\n" +
	"\n" +
	"\x06FEMALE\x10\x02\"/\n" +
	"\x05State\x12\v\n" +
	"\aOFFLINE\x10\x00\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x01\x12\r\n" +
	"\tINVISIBLE\x10\x02B\x05\n" +
	"\x03pet*K\n" +
	"\tGroupRole\x12\x0e\n" +
	"\n" +
	"UNSPECIFIC\x10\x00\x12\v\n" +
	"\aCREATOR\x10\x01\x12\x11\n" +
	"\rADMINISTRATOR\x10\x02\x12\x0e\n" +
	"\n" +
	"VICE_OWNER\x10\x03B\fZ\n" +
	"./testdatab\x06proto3"

var (
	file_testdata_message_proto_rawDescOnce sync.Once
	file_testdata_message_proto_rawDescData []byte
)

func file_testdata_message_proto_rawDescGZIP() []byte {
	file_testdata_message_proto_rawDescOnce.Do(func() {
		file_testdata_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_message_proto_rawDesc), len(file_testdata_message_proto_rawDesc)))
	})
	return file_testdata_message_proto_rawDescData
}

var file_testdata_message_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_testdata_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_testdata_message_proto_goTypes = []any{
	(GroupRole)(0),        // 0: testdata.GroupRole
	(MessageState)(0),     // 1: testdata.message.State
	(MessageManGender)(0), // 2: testdata.message.man.Gender
	(*Dog)(nil),           // 3: testdata.dog
	(*Cat)(nil),           // 4: testdata.cat
	(*Message)(nil),       // 5: testdata.message
	(*MessageMan)(nil),    // 6: testdata.message.man
}
var file_testdata_message_proto_depIdxs = []int32{
	6, // 0: testdata.message.from:type_name -> testdata.message.man
	3, // 1: testdata.message.dog:type_name -> testdata.dog
	4, // 2: testdata.message.cat:type_name -> testdata.cat
	0, // 3: testdata.message.role:type_name -> testdata.GroupRole
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_testdata_message_proto_init() }
func file_testdata_message_proto_init() {
	if File_testdata_message_proto != nil {
		return
	}
	file_testdata_message_proto_msgTypes[2].OneofWrappers = []any{
		(*Message_Dog)(nil),
		(*Message_Cat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_message_proto_rawDesc), len(file_testdata_message_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_message_proto_goTypes,
		DependencyIndexes: file_testdata_message_proto_depIdxs,
		EnumInfos:         file_testdata_message_proto_enumTypes,
		MessageInfos:      file_testdata_message_proto_msgTypes,
	}.Build()
	File_testdata_message_proto = out.File
	file_testdata_message_proto_goTypes = nil
	file_testdata_message_proto_depIdxs = nil
}
